# Generated by Django 4.2 on 2024-03-20 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='Instructor',
            new_name='instructor',
        ),
    ]
